USE [Dispatch]
GO

/****** Object:  Table [dbo].[TC_Archive]    Script Date: 09/10/2021 23:31:20 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TC_Archive]') AND type in (N'U'))
DROP TABLE [dbo].[TC_Archive]
GO

/****** Object:  Table [dbo].[TC_Archive]    Script Date: 09/10/2021 23:31:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TC_Archive](
	[TCID] [int]  NOT NULL,
	[OFFERNUM] [int] NULL,
	[CUST_ACCT] [varchar](10) NULL,
	[SITE_ID] [varchar](10) NULL,
	[CST_NAME] [varchar](100) NULL,
	[ADDRESS] [varchar](512) NULL,
	[MKTTYPE] [varchar](50) NULL,
	[RPHONE] [varchar](50) NULL,
	[MPHONE] [varchar](50) NULL,
	[BPHONE] [varchar](50) NULL,
	[BPHONE_DESC] [varchar](50) NULL,
	[JOB_TYPE] [varchar](10) NULL,
	[JOB_TASK] [varchar](50) NULL,
	[FRC] [varchar](20) NULL,
	[PROB] [varchar](100) NULL,
	[SCH_DATE] [date] NULL,
	[SCH_TIME] [varchar](20) NULL,
	[SQ] [varchar](5) NULL,
	[MUSTDO] [smallint] NULL,
	[INSTALLER] [varchar](5) NULL,
	[Routing] [varchar](5) NULL,
	[UPD_INSTALLER] [varchar](5) NULL,
	[CONTRACTOR] [varchar](50) NULL,
	[ROUTE] [varchar](5) NULL,
	[RA_TEAM] [varchar](50) NULL,
	[PROB1] [varchar](10) NULL,
	[PROB2] [varchar](10) NULL,
	[PROB3] [varchar](10) NULL,
	[PROB4] [varchar](10) NULL,
	[PROB5] [varchar](10) NULL,
	[PROB6] [varchar](10) NULL,
	[FIX] [varchar](10) NULL,
	[FIX1] [varchar](10) NULL,
	[FIX2] [varchar](10) NULL,
	[FIX3] [varchar](10) NULL,
	[FIX4] [varchar](10) NULL,
	[FIX5] [varchar](10) NULL,
	[New_Modem] [varchar](500) NULL,
	[Old_Modem] [varchar](500) NULL,
	[Status_Modem] [varchar](500) NULL,
	[New_Router] [varchar](500) NULL,
	[Old_Router] [varchar](500) NULL,
	[Status_Router] [varchar](500) NULL,
	[EQP] [varchar](50) NULL,
	[Stat_New_EQP] [varchar](500) NULL,
	[Stat_Old_EQP] [varchar](500) NULL,
	[Status_STB] [varchar](500) NULL,
	[STB_NEW] [varchar](500) NULL,
	[STB_OLD] [varchar](500) NULL,
	[CHANGE_SLOTTIME] [varchar](20) NULL,
	[STAT_GD] [varchar](5) NULL,
	[STAT_GC] [varchar](5) NULL,
	[STAT_GT] [varchar](5) NULL,
	[CONF_DUTY] [varchar](5) NULL,
	[CONF_NEED] [smallint] NULL,
	[REASON_CHANGE] [varchar](500) NULL,
	[CONF_BY] [varchar](10) NULL,
	[REMARKS] [varchar](max) NULL,
	[START] [varchar](5) NULL,
	[FINISH] [varchar](5) NULL,
	[REPORT] [varchar](5) NULL,
	[RA] [varchar](5) NULL,
	[CP] [varchar](5) NULL,
	[Closed_By] [varchar](10) NULL,
	[INPUT] [varchar](5) NULL,
	[STATUS1] [varchar](50) NULL,
	[STATUS2] [varchar](50) NULL,
	[STATUS3] [varchar](50) NULL,
	[SCHED_AREA] [varchar](50) NULL,
	[SCA] [varchar](5) NULL,
	[Branch] [varchar](50) NULL,
	[C_AREA] [varchar](50) NULL,
	[OPR] [varchar](50) NULL,
	[WIP_COMMENT] [varchar](512) NULL,
	[CHG_SLOTTIME] [varchar](20) NULL,
	[SMS_CHG_SLOTTIME] [varchar](20) NULL,
	[SMS_PIC] [varchar](10) NULL,
	[NET_RECORDED] [smallint] NULL,
	[NET_REPORTED] [smallint] NULL,
	[NET_PIC] [varchar](10) NULL,
	[CCTS] [smallint] NULL,
	[CCTS_PIC] [varchar](10) NULL,
	[TAP_FULL] [smallint] NULL,
	[TAP_FULL_PIC] [varchar](10) NULL,
	[InputDate] [datetime] NULL,
	[ReportDate] [datetime] NULL,
	[ReportBy] [varchar](50) NULL,
	[UpdateDate] [datetime] NULL,
	[UpdateBy] [varchar](50) NULL,
	[SyncDate] [datetime] NULL,
	[EmailCount] [int] NULL,
	[CheckInStat] [varchar](50) NULL,
	[CheckInBy] [varchar](50) NULL,
	[Closeby_AMD] [varchar](50) NULL,
	[ClosebyStat_AMD] [varchar](50) NULL,
	[SPC_INSTR] [varchar](50) NULL,
	[Confirmation_status] [varchar](50) NULL,
	[isreported] [bit] NULL,
	[CloseDate] [datetime] NULL,
	[FIBERNODE] [varchar](50) NULL,
	[CHRG_CABLE] [varchar](50) NULL,
	[NFRemark] [varchar](2500) NULL,
	[NEW_BOX_TYPE] [varchar](5) NULL,
	[OPR_CREATE] [varchar](10) NULL,
	[SCHTC] [varchar](10) NULL,
	[Smartbox_new] [varchar](225) NULL,
	[Smartbox_old] [varchar](225) NULL,
	[status_smartbox] [varchar](50) NULL,
	[WORDER] [datetime] NULL,
	[TOTAL_TC] [varchar](50) NULL,
	[SDSTB] [varchar](50) NULL,
	[Data_Longitude] [float] NULL,
	[Data_Latitude] [float] NULL,
	[Actual_Longitude] [float] NULL,
	[Actual_Latitude] [float] NULL,
	[AerialCableSerial] [varchar](50) NULL,
	[AerialCableStart] [int] NULL,
	[AerialCableEnd] [int] NULL,
	[Inhouse1Serial] [varchar](50) NULL,
	[Inhouse1Start] [int] NULL,
	[Inhouese1End] [int] NULL,
	[Inhouse2Serial] [varchar](50) NULL,
	[Inhouse2Start] [int] NULL,
	[Inhouese2End] [int] NULL,
	[PRORATE] [money] NULL,
	[ONETIME] [money] NULL,
	[DEPOSIT] [money] NULL,
	[MONTHLYRATE] [money] NULL,
	[Networkid] [varchar](50) NULL,
	[Email] [varchar](500) NULL,
	[PIC] [varchar](50) NULL,
	[ISLAND_NAME] [varchar](500) NULL,
	[Installer_OnlineBooking] [varchar](50) NULL,
	[Contractor_OnlineBooking] [varchar](100) NULL,
	[InstallerTeam_OnlineBooking] [varchar](100) NULL,
	[Installer_Phoneno] [varchar](100) NULL,
	[Installer_Amdocs] [varchar](100) NULL,
	[Contractor_Amdocs] [varchar](100) NULL,
	[Demographics1] [varchar](100) NULL,
	[Amdocs_NDReason] [varchar](50) NULL,
	[Amdocs_NDReasonDesc] [varchar](255) NULL,
	[KTP] [varchar](100) NULL,
	[WONoiseRemark] [varchar](2500) NULL,
	[Amdocs_Product] [varchar](100) NULL,
	[ArchiveDate] [datetime] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


